
package com.hs.loan.certification.server.jiufu.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.macrosky.webservice.biz.ObjectFactory;
import com.macrosky.webservice.biz.RepaymentBody;
import com.macrosky.webservice.biz.ReturnModel;
import com.macrosky.webservice.biz.StrikeBody;
import com.macrosky.webservice.biz.ThirdStrikeBody;
import com.macrosky.webservice.biz.TransHead;
import com.macrosky.webservice.biz.TransModel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanService", targetNamespace = "http://biz.webservice.macrosky.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanService {


    /**
     * 
     * @param transBody
     * @param transHead
     * @return
     *     returns com.macrosky.webservice.biz.ReturnModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "thirdRepaymentUpd", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.ThirdRepaymentUpd")
    @ResponseWrapper(localName = "thirdRepaymentUpdResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.ThirdRepaymentUpdResponse")
    public ReturnModel thirdRepaymentUpd(
        @WebParam(name = "TransHead", targetNamespace = "")
        TransHead transHead,
        @WebParam(name = "TransBody", targetNamespace = "")
        RepaymentBody transBody);

    /**
     * 
     * @param transBody
     * @param transHead
     * @return
     *     returns com.macrosky.webservice.biz.TransModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "thirdStrike", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.ThirdStrike")
    @ResponseWrapper(localName = "thirdStrikeResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.ThirdStrikeResponse")
    public TransModel thirdStrike(
        @WebParam(name = "TransHead", targetNamespace = "")
        TransHead transHead,
        @WebParam(name = "TransBody", targetNamespace = "")
        StrikeBody transBody);

    /**
     * 
     * @param transBody
     * @param transHead
     * @return
     *     returns com.macrosky.webservice.biz.ReturnModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getThirdRepayData", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.GetThirdRepayData")
    @ResponseWrapper(localName = "getThirdRepayDataResponse", targetNamespace = "http://biz.webservice.macrosky.com/", className = "com.macrosky.webservice.biz.GetThirdRepayDataResponse")
    public ReturnModel getThirdRepayData(
        @WebParam(name = "TransHead", targetNamespace = "")
        TransHead transHead,
        @WebParam(name = "TransBody", targetNamespace = "")
        ThirdStrikeBody transBody);

}
